#Script made by Johan#6122
#No copyright.




options:
  prefix: &9Build &7>> &r# this is your prefix before the messages.

#All of the blocks in minecraft is NOT in this so copypaste and change if you want/now how.
#Do not change anything down here if you dont know how it works.

on join:
  if player is op:
    make player execute command "buildoff"
    set {buildmode.state.%player%} to false


command /buildon:
  permission: op
  trigger:
    set {buildmode.state.%player%} to true
    send "{@prefix}&2You are now in &6Buildmode!"





command /buildoff:
  permission: op
  trigger:
    set {buildmode.state.%player%} to false
    send "{@prefix}&cYou left &6Buildmode!"




on break of stone:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of grass block:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of dirt:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on break of brown terracotta:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of spruce planks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of dark oak planks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of spruce log:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of glowstone:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of brown carpet:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of brown stained glass:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of brown stained glass pane:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of ender chest:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of chest:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of dark oak slab:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on break of dark oak stairs:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of dark oak trapdoor:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of cracked stone bricks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of snow block:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on break of ice:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on break of andesite:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on break of stone bricks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on break of string:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on break of oak stairs:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on break of spruce stairs:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on break of spruce leaves:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on break of oak leaves:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event






on break of oak log:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on break of barrier:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on break of glass:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on break of glass pane:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on break of oak trapdoor:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on break of spruce door:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event






on break of dark oak door:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on break of dark oak log:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on break of oak fence:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on break of oak sign:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of stone:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of grass block:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of dirt:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on place of brown terracotta:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of spruce planks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of dark oak planks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of spruce log:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of glowstone:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of brown carpet:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of brown stained glass:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of brown stained glass pane:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of ender chest:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of chest:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of dark oak slab:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event




on place of dark oak stairs:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of dark oak trapdoor:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of cracked stone bricks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of snow block:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on place of ice:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on place of andesite:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on place of stone bricks:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event



on place of string:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on place of oak stairs:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on place of spruce stairs:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on place of spruce leaves:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on place of oak leaves:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event






on place of oak log:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on place of barrier:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on place of glass:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event





on place of glass pane:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on place of oak trapdoor:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on place of spruce door:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event






on place of dark oak door:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on place of dark oak log:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event








on place of oak fence:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event







on place of oak sign:
  if player is op:
    if {buildmode.state.%player%} is false:
      cancel event
      send "&cYou are not in &6buildmode!"
  else:
    cancel event










command /buildstate:
  permission: op
  trigger:
    if {buildmode.state.%player%} is true:
      send "&7-----&fBuildState&7------"
      send "&7You are currently in BuildMode!"
      send "&7-----&fBuildState&7------"
    if {buildmode.state.%player%} is false:
      send "&7-----&fBuildState&7------"
      send "&7You are currently not in BuildMode!"
      send "&7-----&fBuildState&7------"

    
